"""Association files.

Stage-2/3 pipelines consume JSON association files. jwstflow can build them in
three ways (``association.mode`` in the YAML):

``per_exposure``
    One Level-2 association per science exposure; background / imprint
    members are attached with :class:`MemberRule` (header filters + keywords
    that must match the science exposure). This is the manual recipe from the
    jwst docs (``asn_from_list -r DMSLevel2bBase`` + editing members).
``group``
    One Level-3 association per group of exposures sharing ``group_by`` header
    keywords, with an explicit product-name template.
``official``
    Build a pool from the headers (``jwst.associations.mkpool``) and run the
    DMS rule sets. Reproduces what MAST delivers, including instrument-specific
    subtleties. Needs the ``jwst`` package.

The JSON written follows the documented association format, so it is readable
by any jwst version; ``jwst`` itself is only imported for ``official`` mode.
"""

from __future__ import annotations

import json
import logging
import os
import re
from collections import defaultdict
from collections.abc import Iterable, Mapping
from dataclasses import dataclass, field
from datetime import datetime, timezone
from pathlib import Path
from typing import Any

from .config.schema import AssociationConfig, MemberRule
from .data.discovery import FileRecord, match_filters

log = logging.getLogger(__name__)

DEFAULT_RULE = {2: "DMSLevel2bBase", 3: "DMS_Level3_Base"}
DEFAULT_SCIENCE_FILTERS = {
    2: {"IS_IMPRT": False},  # backgrounds are calibrated as their own products
    3: {"BKGDTARG": False, "IS_IMPRT": False},
}


@dataclass
class Association:
    """An association ready to be written."""

    name: str  # file stem, e.g. jw01234-o001_t001_nirspec_g395h-f290lp_spec3
    data: dict[str, Any]
    members: list[Path] = field(default_factory=list)  # every file referenced

    @property
    def filename(self) -> str:
        return f"{self.name}_asn.json"

    def write(self, directory: Path, *, relative: bool = True) -> Path:
        directory = Path(directory)
        directory.mkdir(parents=True, exist_ok=True)
        path = directory / self.filename
        data = json.loads(json.dumps(self.data))  # deep copy, JSON-safe
        for product in data["products"]:
            for member in product["members"]:
                p = Path(member["expname"])
                member["expname"] = (
                    os.path.relpath(p, directory) if relative and p.is_absolute() else str(p)
                )
        path.write_text(json.dumps(data, indent=2) + "\n")
        return path


# ---------------------------------------------------------------------------
# helpers
# ---------------------------------------------------------------------------


def _skeleton(
    *,
    asn_type: str,
    rule: str,
    program: Any,
    asn_id: str,
    pool: str,
    target: str | None = None,
) -> dict[str, Any]:
    return {
        "asn_type": asn_type,
        "asn_rule": rule,
        "version_id": datetime.now(timezone.utc).strftime("%Y%m%dt%H%M%S"),
        "code_version": "jwstflow",
        "degraded_status": "No known degraded exposures in association.",
        "program": f"{int(program):05d}" if str(program).isdigit() else str(program),
        "constraints": "Generated by jwstflow",
        "asn_id": asn_id,
        "target": target or "t001",
        "asn_pool": pool,
        "products": [],
    }


def _optelem(rec: FileRecord) -> str:
    inst = str(rec.get("INSTRUME", "")).upper()
    if inst == "NIRSPEC":
        return f"{rec.get('GRATING', 'none')}-{rec.get('FILTER', 'none')}"
    if inst == "MIRI" and rec.get("CHANNEL"):
        return f"{rec.get('CHANNEL')}-{rec.get('BAND', 'none')}"
    return str(rec.get("FILTER", rec.get("GRATING", "none")))


class _SafeMap(dict):
    def __missing__(self, key: str) -> str:
        return "none"


def product_name(template: str, rec: FileRecord) -> str:
    values = _SafeMap({k: v for k, v in rec.meta.items()})
    values["OPTELEM"] = _optelem(rec)
    if "PROGRAM" in values:
        values["PROGRAM"] = f"{int(values['PROGRAM']):05d}" if str(values["PROGRAM"]).isdigit() else values["PROGRAM"]
    if "OBSERVTN" in values:
        values["OBSERVTN"] = f"{int(values['OBSERVTN']):03d}" if str(values["OBSERVTN"]).isdigit() else values["OBSERVTN"]
    name = template.format_map(values)
    return sanitize(name)


def sanitize(name: str) -> str:
    name = name.strip().lower()
    name = re.sub(r"[^a-z0-9_\-.]+", "-", name)
    return re.sub(r"-{2,}", "-", name).strip("-")


def _matches_member(science: FileRecord, cand: FileRecord, rule: MemberRule) -> bool:
    if cand.path == science.path:
        return False
    if not match_filters(cand.meta, rule.filters):
        return False
    for key in rule.match_on:
        if cand.get(key) != science.get(key):
            return False
    for key in rule.differ_on:
        if cand.get(key) == science.get(key):
            return False
    return True


def _asn_id(rec: FileRecord, level: int) -> str:
    obs = rec.get("OBSERVTN")
    if obs is not None and str(obs).isdigit():
        return f"o{int(obs):03d}"
    return "a2001" if level == 2 else "a3001"


# ---------------------------------------------------------------------------
# builders
# ---------------------------------------------------------------------------


def build_associations(
    records: list[FileRecord], cfg: AssociationConfig, *, asn_type: str, stage: str
) -> list[Association]:
    if cfg.mode == "per_exposure":
        return per_exposure(records, cfg, asn_type=asn_type, stage=stage)
    if cfg.mode == "group":
        return grouped(records, cfg, asn_type=asn_type, stage=stage)
    return official(records, cfg, stage=stage)


def per_exposure(
    records: list[FileRecord], cfg: AssociationConfig, *, asn_type: str, stage: str
) -> list[Association]:
    filters = cfg.science_filters or DEFAULT_SCIENCE_FILTERS[2]
    rule = cfg.rule or DEFAULT_RULE[cfg.level]
    science = [r for r in records if match_filters(r.meta, filters)]
    out: list[Association] = []
    for sci in science:
        data = _skeleton(
            asn_type=asn_type,
            rule=rule,
            program=sci.get("PROGRAM", 0),
            asn_id=_asn_id(sci, 2),
            pool=f"jwstflow_{stage}",
        )
        members = [{"expname": str(sci.path.resolve()), "exptype": "science"}]
        paths = [sci.path]
        for mrule in cfg.members:
            for cand in records:
                if _matches_member(sci, cand, mrule):
                    members.append({"expname": str(cand.path.resolve()), "exptype": mrule.exptype})
                    paths.append(cand.path)
        data["products"].append({"name": sci.stem, "members": members})
        out.append(Association(f"{sci.stem}_{asn_type}", data, paths))
    return out


def grouped(
    records: list[FileRecord], cfg: AssociationConfig, *, asn_type: str, stage: str
) -> list[Association]:
    filters = cfg.science_filters or DEFAULT_SCIENCE_FILTERS[3]
    rule = cfg.rule or DEFAULT_RULE[cfg.level]
    science = [r for r in records if match_filters(r.meta, filters)]
    groups: dict[tuple[Any, ...], list[FileRecord]] = defaultdict(list)
    for r in science:
        groups[tuple(r.get(k) for k in cfg.group_by)].append(r)
    out: list[Association] = []
    used: set[str] = set()
    for key, recs in groups.items():
        first = recs[0]
        name = product_name(cfg.product_name, first)
        # the association file / task label must be unique per group even when the
        # product name is not (e.g. DMS-style IFU names without the grating: the
        # pipeline's cube_build appends the grating-filter suffix itself)
        label = name
        if label in used:
            label = sanitize(f"{name}_{'-'.join(str(v) for v in key if v is not None)}")
        used.add(label)
        data = _skeleton(
            asn_type=asn_type,
            rule=rule,
            program=first.get("PROGRAM", 0),
            asn_id=_asn_id(first, 3),
            pool=f"jwstflow_{stage}",
            target=sanitize(str(first.get("TARGPROP", "t001"))),
        )
        members = [{"expname": str(r.path.resolve()), "exptype": "science"} for r in recs]
        paths = [r.path for r in recs]
        for mrule in cfg.members:
            seen: set[Path] = set()
            for sci in recs:
                for cand in records:
                    if cand.path in seen or cand.path in paths:
                        continue
                    if _matches_member(sci, cand, mrule):
                        seen.add(cand.path)
                        members.append(
                            {"expname": str(cand.path.resolve()), "exptype": mrule.exptype}
                        )
                        paths.append(cand.path)
        data["products"].append({"name": name, "members": members})
        out.append(Association(f"{label}_{asn_type}", data, paths))
    return out


def official(records: list[FileRecord], cfg: AssociationConfig, *, stage: str) -> list[Association]:
    """Run the jwst association generator on a pool built from the file headers.

    The DMS rules expect Level-1b (``_uncal``) names and rewrite them to
    ``_rate``/``_cal`` themselves, so the pool is fed ``<stem>_uncal.fits``
    names and the generated member names are mapped back to the real files by
    exposure stem. Exposures the rules reject are reported at WARNING level.
    """
    try:
        from jwst.associations import AssociationRegistry, generate
        from jwst.associations.lib.utilities import constrain_on_candidates
        from jwst.associations.mkpool import mkpool
    except ImportError as exc:
        raise RuntimeError("association.mode=official needs the `jwst` package") from exc
    import jwst.associations.lib as asnlib

    if not records:
        return []
    which = cfg.official_rules or ("level2" if cfg.level == 2 else "level3")
    rules_file = Path(asnlib.__file__).parent / (
        "rules_level2b.py" if which == "level2" else "rules_level3.py"
    )
    pool = mkpool([str(r.path) for r in records])
    pool["filename"] = [f"{r.stem}_uncal.fits" for r in records]
    # mkpool fills these "pool-only" columns with constants (in DMS they come from
    # the proposal database, not from headers); recover them from the headers.
    pool["is_imprt"] = ["t" if r.meta.get("IS_IMPRT") else "f" for r in records]
    pool["pntgtype"] = [str(r.meta.get("PNTGTYPE") or "science").lower() for r in records]
    registry = AssociationRegistry(
        definition_files=[str(rules_file)],
        include_default=False,
        # same global constraint `asn_generate` applies: without it every
        # association is a "discovered" (aNNNN) candidate and level 2 drops them
        global_constraints=constrain_on_candidates(None),
    )
    asns = generate(pool, registry)
    by_stem = {r.stem: r.path.resolve() for r in records}
    out: list[Association] = []
    for asn in asns:
        _fname, serialized = asn.dump()
        data = json.loads(serialized)
        data["asn_pool"] = f"jwstflow_{stage}"
        paths: list[Path] = []
        for product in data.get("products", []):
            kept = []
            for member in product.get("members", []):
                stem = FileRecord(Path(member["expname"])).stem
                p = by_stem.get(stem)
                if p is None:
                    log.warning("official asn %s: member %s has no matching input; dropped", data.get("asn_id"), member["expname"])
                    continue
                member["expname"] = str(p)
                paths.append(p)
                kept.append(member)
            product["members"] = kept
        data["products"] = [pr for pr in data["products"] if pr["members"]]
        if not data["products"]:
            continue
        first = data["products"][0]["name"]
        out.append(Association(sanitize(f"{first}_{data.get('asn_type', 'asn')}"), data, paths))
    if not out:
        log.warning("official association generator produced no %s associations", which)
    return out


def write_all(asns: Iterable[Association], directory: Path, *, relative: bool = True) -> list[Path]:
    return [a.write(directory, relative=relative) for a in asns]


def members_of(asn_path: Path) -> list[Path]:
    """Member paths referenced by an association file on disk."""
    data = json.loads(Path(asn_path).read_text())
    base = Path(asn_path).parent
    out: list[Path] = []
    for product in data.get("products", []):
        for member in product.get("members", []):
            p = Path(member["expname"])
            out.append(p if p.is_absolute() else (base / p))
    return out


def summarize(data: Mapping[str, Any]) -> str:
    parts = []
    for product in data.get("products", []):
        counts: dict[str, int] = defaultdict(int)
        for m in product.get("members", []):
            counts[m.get("exptype", "?")] += 1
        parts.append(f"{product.get('name')}: " + ", ".join(f"{v} {k}" for k, v in counts.items()))
    return "; ".join(parts)
